# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-04-08 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initadmin', '0003_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='is_party_member',
            field=models.BooleanField(default=False),
        ),
    ]
