from django.conf.urls import url, include
from django.views import generic
from . import views

urlpatterns = [
	# globals
    url('^$', views.index, name='home'),
    url('^agora$', views.agora, name='agora'),
    url('^archiv$', views.archive, name='archive'),
    url('^thema/(?P<topic_id>\d+)(?:-(?P<slug>.+))?$', views.topic, name="topic"),
    url('^thema-archiv/(?P<topic_id>\d+)(?:-(?P<slug>.+))?$', views.topic, {'archive': True}, name="topic_archive"),
    url('^issue-archiv/(?P<issue_id>\d+)(?:-(?P<slug>.+))?$', views.issue_item, {'archive': True}, name="issue_archive"),
    url('^solution-archiv/(?P<solution_id>\d+)(?:-(?P<slug>.+))?$', views.solution_item, {'archive': True}, name="solution_item_archive"),
    url('^(?P<topic_id>\d+)(?:-(?P<slug>.+))?/beitrag/new$', views.new_contribution, name="new_contribution"),
    url('^(?P<issue_id>\d+)(?:-(?P<slug>.+))?/solution/new$', views.new_solution, name="new_solution"),
    url('^initiative/new$', views.new, name="new_initiative"),
    url('^issue/new$', views.new_issue, name="new_issue"),
    url('^user_autocomplete$', views.UserAutocomplete.as_view(), name='user_autocomplete'),
    url(r'^su/', include('django_su.urls')),

    # initiative specifics
    url('^ueber/$', views.ueber, name="ueber"),
    url('^initiative/new$', views.new, name="new_initiative"),
    url(r'^issue/(?P<issue_id>\d+)(?:-(?P<slug>.+))?/support$', views.issue_support),
    url(r'^(?P<initype>initiative|ao-aenderung)/(?P<init_id>\d+)(?:-(?P<slug>.+))?/support$', views.support),
    url(r'^(?P<initype>initiative|ao-aenderung)/(?P<init_id>\d+)(?:-(?P<slug>.+))?/ack_support$', views.ack_support),
    url(r'^issue/(?P<issue_id>\d+)(?:-(?P<slug>.+))?/ack_support$', views.issue_ack_support),
    url(r'^(?P<initype>initiative|ao-aenderung)/(?P<init_id>\d+)(?:-(?P<slug>.+))?/rm_support$', views.rm_support),
    url(r'^issue/(?P<issue_id>\d+)(?:-(?P<slug>.+))?/rm_support$', views.issue_rm_support),
    url(r'^issue/(?P<issue_id>\d+)(?:-(?P<slug>.+))?/(?P<user_id>\d+)/rm_user_support$', views.issue_rm_user_support),
    url(r'^(?P<initype>initiative|ao-aenderung|plenumsentscheidung|plenumsabwaegung|beitrag)/(?P<init_id>\d+)(?:-(?P<slug>.+))?/edit$', views.edit),
    url(r'^issue/(?P<issue_id>\d+)(?:-(?P<slug>.+))?/edit$', views.issue_edit),
    url(r'^solution/(?P<solution_id>\d+)(?:-(?P<slug>.+))?/edit$', views.solution_edit),
    url(r'^(?P<initype>initiative|ao-aenderung)/(?P<init_id>\d+)(?:-(?P<slug>.+))?/submit_to_committee$', views.submit_to_committee),
    url(r'^issue/(?P<issue_id>\d+)(?:-(?P<slug>.+))?/submit_to_review$', views.submit_to_review),
    url(r'^issue/(?P<issue_id>\d+)(?:-(?P<slug>.+))?/delete$', views.issue_delete),
    url(r'^solution/(?P<solution_id>\d+)(?:-(?P<slug>.+))?/delete$', views.solution_delete),
    url(r'^moderation/(?P<moderation_id>\d+)/delete$', views.moderation_delete),
    url(r'^(?P<initype>beitrag)/(?P<init_id>\d+)(?:-(?P<slug>.+))?/new_question$', views.new_question),
    url(r'^solution/(?P<solution_id>\d+)(?:-(?P<slug>.+))?/new_question$', views.solution_new_question),
    url(r'^(?P<initype>initiative|ao-aenderung|beitrag)/(?P<init_id>\d+)(?:-(?P<slug>.+))?/new_argument$', views.new_argument),
    url(r'^solution/(?P<solution_id>\d+)(?:-(?P<slug>.+))?/new_argument$', views.solution_new_argument),
    url(r'^(?P<initype>initiative|ao-aenderung|beitrag)/(?P<init_id>\d+)(?:-(?P<slug>.+))?/new_proposal$', views.new_proposal),
    url(r'^(?P<initype>initiative|ao-aenderung)/(?P<init_id>\d+)(?:-(?P<slug>.+))?/new_moderation$', views.moderate),
    url(r'^issue/(?P<issue_id>\d+)(?:-(?P<slug>.+))?/new_review$', views.review),
    url(r'^solution/(?P<solution_id>\d+)(?:-(?P<slug>.+))?/new_review$', views.solution_review),
    url(r'^issue/(?P<issue_id>\d+)(?:-(?P<slug>.+))?/veto$', views.veto),
    url(r'^(?P<initype>initiative|ao-aenderung|plenumsentscheidung|plenumsabwaegung)/(?P<init_id>\d+)(?:-(?P<slug>.+))?/vote$', views.vote, name="vote"),
    url(r'^(?P<initype>plenumsabwaegung)/(?P<init_id>\d+)(?:-(?P<slug>.+))?/preference$', views.preference, name="preference"),
    url(r'^(?P<initype>beitrag)/(?P<init_id>\d+)(?:-(?P<slug>.+))?/resistance', views.resistance, name="resistance"),
    url(r'^topic/(?P<topic_id>\d+)(?:-(?P<slug>.+))?/resistances$', views.topic_resistances, name="topic_resistances"),
    url(r'^issue/(?P<issue_id>\d+)(?:-(?P<slug>.+))?/resistances$', views.issue_resistances, name="issue_resistances"),
    url(r'^(?P<initype>initiative|ao-aenderung|plenumsentscheidung)/(?P<init_id>\d+)(?:-(?P<slug>.+))?/reset_vote$', views.reset_vote, name="reset_vote"),
    url(r'^(?P<initype>plenumsabwaegung)/(?P<init_id>\d+)(?:-(?P<slug>.+))?/reset_preference$', views.reset_preference, name="reset_preference"),
    url(r'^(?P<initype>beitrag)/(?P<init_id>\d+)(?:-(?P<slug>.+))?/reset_resistance$', views.reset_resistance, name="reset_resistance"),
    url(r'^topic/(?P<topic_id>\d+)(?:-(?P<slug>.+))?/reset_resistances$', views.reset_topic_resistances, name="reset_topic_resistances"),
    url(r'^issue/(?P<issue_id>\d+)(?:-(?P<slug>.+))?/reset_resistances$', views.reset_issue_resistances, name="reset_issue_resistances"),
    url(r'^(?P<initype>initiative|ao-aenderung|plenumsentscheidung|plenumsabwaegung|beitrag)/(?P<init_id>\d+)(?:-(?P<slug>.+))?/compare/(?P<version_id>\d+)$', views.compare),
    url(r'^issue/(?P<issue_id>\d+)(?:-(?P<slug>.+))?/compare/(?P<version_id>\d+)$', views.issue_compare),
    url(r'^solution/(?P<solution_id>\d+)(?:-(?P<slug>.+))?/compare/(?P<version_id>\d+)$', views.solution_compare),
    url(r'^(?P<initype>initiative|ao-aenderung)/(?P<init_id>\d+)(?:-(?P<slug>.+))?/invite/(?P<invite_type>.*)$', views.invite),
    url(r'^issue/(?P<issue_id>\d+)(?:-(?P<slug>.+))?/invite/(?P<invite_type>.*)$', views.issue_invite),
    url(r'^(?P<initype>initiative|ao-aenderung)/(?P<init_id>\d+)(?:-(?P<slug>.+))?/moderation/(?P<target_id>\d+)$', views.show_moderation),
    url(r'^issue/(?P<issue_id>\d+)(?:-(?P<slug>.+))?/issue_review/(?P<target_id>\d+)$', views.show_review),
    url(r'^solution/(?P<solution_id>\d+)(?:-(?P<slug>.+))?/solution_review/(?P<target_id>\d+)$', views.show_solution_review),
    url(r'^(?P<initype>initiative|ao-aenderung|beitrag)/(?P<init_id>\d+)(?:-(?P<slug>.+))?/(?P<target_type>.*)/(?P<target_id>\d+)$', views.show_resp),
    url(r'^solution/(?P<solution_id>\d+)(?:-(?P<slug>.+))?/(?P<target_type>.*)/(?P<target_id>\d+)$', views.solution_show_resp),
    url(r'^(?P<initype>initiative|ao-aenderung|plenumsentscheidung|plenumsabwaegung|beitrag)/(?P<init_id>\d+)(?:-(?P<slug>.+))?$', views.item, name="initiative_item"),
    url('^issue/(?P<issue_id>\d+)(?:-(?P<slug>.+))?$', views.issue_item, name="issue_item"),
    url('^issue/(?P<issue_id>\d+)(?:-(?P<slug>.+))?$', views.issue_item, name="issue"),
    url('^solution/(?P<solution_id>\d+)(?:-(?P<slug>.+))?$', views.solution_item, name="solution_item"),
    url('^comment/(?P<target_type>.*)/(?P<target_id>\d+)$', views.comment),
    url('^like/(?P<target_type>.*)/(?P<target_id>\d+)$', views.like),
    url('^unlike/(?P<target_type>.*)/(?P<target_id>\d+)$', views.unlike),
    url('^ao-aenderung/new$', views.new_policychange, name="new_policychange"),
    url('^plenumsentscheidung/new$', views.new_plenumvote, name="new_plenumvote"),
    url('^plenumsabwaegung/new$', views.new_plenumoptions, name="new_plenumoptions"),
    url(r'^(?P<initype>ao-aenderung)/(?P<init_id>\d+)(?:-(?P<slug>.+))?/start_discussion_phase$', views.start_discussion_phase),
    url(r'^(?P<initype>beitrag)/(?P<init_id>\d+)(?:-(?P<slug>.+))?/start_support_phase$', views.start_support_phase),
    url(r'^(?P<initype>plenumsentscheidung|plenumsabwaegung)/(?P<init_id>\d+)(?:-(?P<slug>.+))?/start_voting$', views.start_voting)

]
