# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 15:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('argument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initproc.Argument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemandingVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('n', 'new'), ('d', 'discussion'), ('v', 'voting'), ('a', 'accepted'), ('d', 'denied')], max_length=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField()),
                ('forderung', models.TextField()),
                ('kosten', models.TextField()),
                ('fin_vorschlag', models.TextField()),
                ('arbeitsweise', models.TextField()),
                ('init_argument', models.TextField()),
                ('einordgnung', models.CharField(max_length=50)),
                ('ebene', models.CharField(max_length=50)),
                ('bereich', models.CharField(max_length=50)),
                ('went_to_discussion_at', models.DateTimeField(blank=True)),
                ('went_to_voting_at', models.DateTimeField(blank=True)),
                ('was_closed_at', models.DateTimeField(blank=True)),
                ('initiators', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField(default=True)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initproc.Initiative')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('in_favor', models.BooleanField(default=True)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initproc.Initiative')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='demandingvote',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initproc.Initiative'),
        ),
        migrations.AddField(
            model_name='demandingvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='argument',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initproc.Initiative'),
        ),
        migrations.AddField(
            model_name='argument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('user', 'initiative')]),
        ),
        migrations.AlterUniqueTogether(
            name='supporter',
            unique_together=set([('user', 'initiative')]),
        ),
        migrations.AlterUniqueTogether(
            name='demandingvote',
            unique_together=set([('user', 'initiative')]),
        ),
    ]
