# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='went_public_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supporter',
            name='first',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='bereich',
            field=models.CharField(choices=[('Mitbestimmung', 'Mitbestimmung'), ('Transparenz und Lobbyismus', 'Transparenz und Lobbyismus'), ('Demokratisches und solidarisches Europa', 'Demokratisches und solidarisches Europa'), ('Gerechtigkeit und Verantwortung füreinander', 'Gerechtigkeit und Verantwortung füreinander'), ('Vielfältige, weltoffene und inklusive Gesellschaft', 'Vielfältige, weltoffene und inklusive Gesellschaft'), ('Nachhaltigkeit', 'Nachhaltigkeit'), ('Zukunft aktiv gestalten', 'Zukunft aktiv gestalten'), ('(andere)', '(andere)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='ebene',
            field=models.CharField(choices=[('Bund', 'Bund')], max_length=50),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='einordnung',
            field=models.CharField(choices=[('Einzellinitiatve', 'Einzellinitiative')], max_length=50),
        ),
    ]
