# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0003_auto_20170314_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='quorum',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='state',
            field=models.CharField(choices=[('n', 'new'), ('d', 'discussion'), ('v', 'voting'), ('a', 'accepted'), ('r', 'rejected')], max_length=1),
        ),
    ]
