# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0003_auto_20170606_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quorum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quorum', models.IntegerField(null=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='initiative',
            name='quorum',
        ),
    ]
