# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0004_auto_20170314_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='in_favor',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='demandingvote',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='initproc.Initiative'),
        ),
        migrations.AlterField(
            model_name='supporter',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporters', to='initproc.Initiative'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='initproc.Initiative'),
        ),
    ]
