# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0004_auto_20170606_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='problem',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initiative',
            name='subtitle',
            field=models.CharField(default=' ', max_length=1024),
            preserve_default=False,
        ),
    ]
