# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 09:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def migrate_initiators(apps, schema_editor):
    # Let's move the previous direct relationship
    # over to a certain type of supporter instead
    Initiative = apps.get_model('initproc', 'Initiative')
    Supporter = apps.get_model('initproc', 'Supporter')
    for ini in Initiative.objects.all():
        for initiator in ini.initiators.all():
            try:
                sup = Supporter.objects.get(user=initiator.id, initiative=ini.id)
            except Supporter.DoesNotExist:
                sup = Supporter(initiative=ini.id, user=initiator.id, first=True, initiator=True, public=True).save()
            else:
                sup.initiator = True
                sup.first = True
                sup.public = True
                sup.save()


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0005_auto_20170607_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='supporters',
            field=models.ManyToManyField(through='initproc.Supporter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supporter',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting', to='initproc.Initiative'),
        ),
        migrations.AddField(
            model_name='supporter',
            name='ack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supporter',
            name='initiator',
            field=models.BooleanField(default=False),
        ),

        migrations.RunPython(migrate_initiators),
        migrations.RemoveField(
            model_name='initiative',
            name='initiators',
        ),
    ]
