# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0005_auto_20170317_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='argument',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='demandingvote',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='initiative',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='supporter',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='argument',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='initproc.Initiative'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='argument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='initproc.Argument'),
        ),
    ]
