# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-23 15:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def delete_old_likes_and_comments(apps, schema_editor):
    # Let's move the previous direct relationship
    # over to a certain type of supporter instead
    Like = apps.get_model('initproc', 'Like')
    Comment = apps.get_model('initproc', 'Comment')
    Like.objects.all().delete()
    Comment.objects.all().delete()



class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('initproc', '0006_auto_20170616_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80)),
                ('text', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80)),
                ('text', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='argument',
            name='initiative',
        ),
        migrations.RemoveField(
            model_name='argument',
            name='user',
        ),
        migrations.RunPython(delete_old_likes_and_comments),
        migrations.RemoveField(
            model_name='comment',
            name='argument',
        ),
        migrations.AddField(
            model_name='comment',
            name='target_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='target_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='target_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='target_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='einordnung',
            field=models.CharField(choices=[('Einzellinitiatve', 'Einzelinitiative')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('user', 'target_type', 'target_id')]),
        ),
        migrations.RemoveField(
            model_name='like',
            name='argument',
        ),
        migrations.AddField(
            model_name='proposal',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initproc.Initiative'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pro',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initproc.Initiative'),
        ),
        migrations.AddField(
            model_name='pro',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contra',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initproc.Initiative'),
        ),
        migrations.AddField(
            model_name='contra',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Argument',
        ),
    ]
