# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 21:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('initproc', '0007_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('user', 'argument')]),
        ),
    ]
