# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-25 08:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('initproc', '0008_auto_20170625_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('stale', models.BooleanField(default=False)),
                ('vote', models.CharField(choices=[('y', 'okay'), ('a', 'abstain'), ('r', 'request'), ('n', 'no!')], max_length=1)),
                ('text', models.CharField(blank=True, max_length=500)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderations', to='initproc.Initiative')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
