# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-25 13:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('initproc', '0009_moderation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moderation',
            unique_together=set([('user', 'initiative')]),
        ),
    ]
