# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-26 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0010_auto_20170625_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='arbeitsweise',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='fin_vorschlag',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='forderung',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='init_argument',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='kosten',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='problem',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='state',
            field=models.CharField(choices=[('p', 'preparation'), ('i', 'new arrivals'), ('s', 'seeking support'), ('d', 'in discussion'), ('e', 'final edits'), ('m', 'with moderation team'), ('h', 'hidden'), ('v', 'is being voted on'), ('a', 'was accepted'), ('r', 'was rejected')], max_length=1),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='subtitle',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
