# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-26 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0012_comment_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contra',
            name='title',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='pro',
            name='title',
            field=models.CharField(max_length=140),
        ),
    ]
