# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0014_proposal_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='variant_of',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='initproc.Initiative'),
        ),
    ]
