# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-10 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0016_vote_reason'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moderation',
            unique_together=set([]),
        ),
    ]
