# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-08 16:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
from django.contrib.auth import get_user_model
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0018_auto_20170808_1628.py'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='eligible_voters',
            field=models.IntegerField(blank=True, null=True),
            preserve_default=False,
        )
    ]