# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-08 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0018_merge_20170717_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='eligible_voters',
            field=models.IntegerField(default=200, null=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='initiative',
            name='einordnung',
            field=models.CharField(choices=[('Einzelinitiative', 'Einzelinitiative')], max_length=50),
        ),
    ]
