# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-03 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0018_auto_20170808_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderation',
            name='constitution_change',
            field=models.BooleanField(default=False),
        ),
    ]
