# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-24 19:38
# modified by tizip
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0019_auto_20170808_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='value',
            field=models.IntegerField(choices=[(1, 'Ja'), (0, 'Nein'), (2, 'Enthaltung')], default=0),
            preserve_default=False,
        )
    ]
