# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-07 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0020_auto_20170903_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='initiative',
            name='tags',
            field=models.ManyToManyField(to='initproc.Tag'),
        ),
    ]
