# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-24 19:38
# modified by tizip
from __future__ import unicode_literals

from django.db import migrations, models


def init_vote_value(apps, schema_editor):
    # Copy the previous in_favor content to value field
    Vote = apps.get_model('initproc', 'Vote')
    Vote.objects.filter(in_favor=False).update(value=0)
    Vote.objects.filter(in_favor=True).update(value=1)

def reverse_vote_value(apps, schema_editor):
    # Copy the value content back to in_favor
    Vote = apps.get_model('initproc', 'Vote')
    Vote.objects.filter(value=1).update(in_favor=True)

class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0021_auto_20170924_1938'),
    ]

    operations = [
        migrations.RunPython(init_vote_value,
                             reverse_code=reverse_vote_value),
        migrations.RemoveField(
            model_name='vote',
            name='in_favor',
        ),
    ]
