# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-03 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0022_auto_20170924_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='einordnung',
            field=models.CharField(choices=[('Einzelinitiative', 'Einzelinitiative')], max_length=50),
        ),
    ]
