# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-03 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0022_auto_20170924_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='bereich',
            field=models.CharField(choices=[('Globale Politik & internationale Zusammenarbeit', 'Globale Politik & internationale Zusammenarbeit'), ('Bildung, Forschung & Kultur', 'Bildung, Forschung & Kultur'), ('Innenpolitik', 'Innenpolitik'), ('Netz- & Medienpolitik', 'Netz- & Medienpolitik'), ('Geschlechtergerechtigkeit', 'Geschlechtergerechtigkeit'), ('Vielfalt & Integration', 'Vielfalt & Integration'), ('Demokratie & Transparenz', 'Demokratie & Transparenz'), ('Gesundheit, Ernährung & Verbraucher*innenschutz', 'Gesundheit, Ernährung & Verbraucher*innenschutz'), ('Umwelt, Mobilität, Infrastruktur & Strukturentwicklung', 'Umwelt, Mobilität, Infrastruktur & Strukturentwicklung'), ('Soziale Gerechtigkeit, Wirtschaft, Arbeit & Finanzen', 'Soziale Gerechtigkeit, Wirtschaft, Arbeit & Finanzen'), ('Anderes', 'Anderes')], max_length=50),
        ),
    ]
