# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-06 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0023_auto_20180506_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='type',
            field=models.CharField(choices=[('ini', 'initiative'), ('pol', 'policychange'), ('bal', 'ballotvote')], default='initiative', max_length=3),
            preserve_default=False,
        ),
    ]
