# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-11 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0022_auto_20170924_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('subtitle', models.CharField(blank=True, max_length=1024)),
                ('state', models.CharField(choices=[('p', 'preparation'), ('d', 'in discussion'), ('e', 'final edits'), ('v', 'is being voted on'), ('a', 'was accepted'), ('r', 'was rejected')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField(blank=True)),
                ('bereich', models.CharField(choices=[('AO-Änderung', 'AO-Änderung')], max_length=50)),
                ('went_to_discussion_at', models.DateField(blank=True, null=True)),
                ('went_to_voting_at', models.DateField(blank=True, null=True)),
                ('was_closed_at', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
