# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-10 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0023_auto_20180503_1355'),
        ('initproc', '0023_update-subject-categories'),
    ]

    operations = [
    ]
