# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-06 09:50
from __future__ import unicode_literals

from django.db import migrations, models

def init_einordnung(apps, schema_editor):
    # Update German einordnung value to new technical value
    ini = apps.get_model('initproc', 'Initiative')
    ini.objects.all().update(einordnung='initiative')
    migrations.RunSQL("""
    'ALTER TABLE Initiative ADD CONSTRAINT einordnung_values CHECK (
    einordnung in ('initiative', 'ao-aenderung', 'urabstimmung'));'
    """)

def reverse_einordnung(apps, schema_editor):
    # Delete technical value and use German einordnung value
    ini = apps.get_model('initproc', 'Initiative')
    ini.objects.filter(einordnung='initiative').update(einordnung='Einzelinitiative')
    migrations.RunSQL('ALTER TABLE Initiative DROP CONSTRAINT einordnung_values;')

class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0024_merge_20180510_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='einordnung',
            field=models.CharField(choices=[('initiative', 'Einzelinitiative'), ('ao-aenderung', 'AO-Änderung'), ('urabstimmung', 'Urabstimmung')], max_length=50),
        ),
        migrations.RunPython(init_einordnung,
                             reverse_code=reverse_einordnung),
    ]

