# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-26 14:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('initproc', '0024_policychange'),
    ]

    operations = [
        migrations.AddField(
            model_name='policychange',
            name='board',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='policychange',
            name='state',
            field=models.CharField(choices=[('p', 'preparation'), ('d', 'in discussion'), ('e', 'final edits'), ('v', 'is being voted on'), ('a', 'was accepted'), ('r', 'was rejected'), ('h', 'hidden')], max_length=1),
        ),
    ]
