# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-23 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0025_initiative_type'),
        ('initproc', '0026_longer_subject_categories'),
    ]

    operations = [
    ]
