# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-24 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0026_longer_subject_categories'),
        ('initproc', '0025_auto_20180623_1619'),
    ]

    operations = [
    ]
