# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-28 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0028_team_delegation_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='long_description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='team',
            name='short_description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='initproc.Team'),
        ),
    ]
