# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-09 21:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('initproc', '0028_abstimmung_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('value', models.IntegerField()),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='initproc.Option')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='initiative',
            name='einordnung',
            field=models.CharField(choices=[('initiative', 'Einzelinitiative'), ('ao-aenderung', 'AO-Änderung'), ('urabstimmung', 'Urabstimmung'), ('plenumsentscheidung', 'Plenumsentscheidung'), ('plenumsabwaegung', 'Plenumsabwägung')], max_length=50),
        ),
        migrations.AddField(
            model_name='option',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='initproc.Initiative'),
        ),
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together=set([('user', 'option')]),
        ),
    ]
