# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-02-26 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0031_options_and_preferences_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='state',
            field=models.CharField(choices=[('p', 'preparation'), ('i', 'new arrivals'), ('s', 'seeking support'), ('d', 'in discussion'), ('e', 'final edits'), ('m', 'with moderation team'), ('h', 'hidden'), ('v', 'is being voted on'), ('c', 'was completed'), ('a', 'was accepted'), ('r', 'was rejected')], max_length=1),
        ),
    ]
