# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-02 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0034_agora'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='closes_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='motivation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='subtitle',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
