# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-04-10 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0037_anonymize_avatars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='closed_at',
        ),
    ]
