# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-03-13 10:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('initproc', '0039_auto_20200219_1154'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moderation',
            unique_together=set([('user', 'solution'), ('user', 'initiative'), ('user', 'issue')]),
        ),
        migrations.AlterUniqueTogether(
            name='resistance',
            unique_together=set([('user', 'contribution'), ('user', 'solution')]),
        ),
        migrations.AlterUniqueTogether(
            name='supporter',
            unique_together=set([('user', 'initiative'), ('user', 'issue')]),
        ),
    ]
