# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-05-24 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0040_auto_20200313_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resistance',
            name='reason',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
