# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-09-06 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initproc', '0042_auto_20200527_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='motivation',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
